USE [master]
GO

/****** Object:  Database [tenants]    Script Date: 27/03/2022 22:29:08 ******/
CREATE DATABASE [tenants]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tenants', FILENAME = N'C:\Program Files\Microsoft 2\MSSQL15.SQLEXPRESS01\MSSQL\DATA\tenants.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tenants_log', FILENAME = N'C:\Program Files\Microsoft 2\MSSQL15.SQLEXPRESS01\MSSQL\DATA\tenants.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tenants].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tenants] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [tenants] SET ANSI_NULLS ON 
GO

ALTER DATABASE [tenants] SET ANSI_PADDING ON 
GO

ALTER DATABASE [tenants] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [tenants] SET ARITHABORT ON 
GO

ALTER DATABASE [tenants] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tenants] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tenants] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tenants] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tenants] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [tenants] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [tenants] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tenants] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [tenants] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tenants] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tenants] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tenants] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tenants] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tenants] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tenants] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tenants] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tenants] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tenants] SET RECOVERY FULL 
GO

ALTER DATABASE [tenants] SET  MULTI_USER 
GO

ALTER DATABASE [tenants] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tenants] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tenants] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tenants] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [tenants] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tenants] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [tenants] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tenants] SET  READ_WRITE 
GO

